language: rust
rust:
  - 1.31.0
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
sudo: false
env:
  global:
    - RUSTFLAGS="--deny warnings"
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES=""  # default configuration
script:
  - cargo test $FEATURES
  - cargo test --benches $FEATURES -- --test
  - cd fuzz && cargo check
notifications:
  email:
    on_success: never
